# Generated by Django 3.2 on 2024-01-21 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Введите корректный цвет в HEX формате (например, #123ABC или #123).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Цвет тега в HEX'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=200, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[-a-zA-Z0-9_]+$')], verbose_name='Cлаг'),
        ),
    ]
