# Generated by Django 3.2 on 2024-01-21 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240121_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='recipes/', verbose_name='Картинка блюда'),
            preserve_default=False,
        ),
    ]
